# Generated by Django 4.2.5 on 2023-09-29 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('age', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jump_height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('mRSI', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('time_to_takeoff', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('breaking_phase', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('peak_relative_propulsive_power', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('braking_power', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('propulsive_net_impulse', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('lr_avg_braking_force', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('accumulated_acceleration_load', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('accumulated_acceleration_load_pm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_distance_session', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_distance_week', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_speed', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_jump_height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('change_of_orientation', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('training_impulse', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('training_status', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bamalytics.player')),
                ('practice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bamalytics.practice')),
            ],
        ),
    ]
