# Generated by Django 4.2.5 on 2023-10-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.IntegerField(default=-100, primary_key=True, serialize=False),
        ),
    ]
